// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: chats.sql

package pgdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getChatMembers = `-- name: GetChatMembers :many
SELECT user_id
FROM chat_members
WHERE chat_id = $1
`

func (q *Queries) GetChatMembers(ctx context.Context, chatID pgtype.UUID) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, getChatMembers, chatID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.UUID
	for rows.Next() {
		var user_id pgtype.UUID
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
