// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package pgdb

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Chat struct {
	ID        pgtype.UUID        `json:"id"`
	Name      pgtype.Text        `json:"name"`
	IsGroup   bool               `json:"is_group"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type ChatMember struct {
	ChatID   pgtype.UUID        `json:"chat_id"`
	UserID   pgtype.UUID        `json:"user_id"`
	Role     string             `json:"role"`
	JoinedAt pgtype.Timestamptz `json:"joined_at"`
}

type Message struct {
	ID        pgtype.UUID        `json:"id"`
	ChatID    pgtype.UUID        `json:"chat_id"`
	SenderID  pgtype.UUID        `json:"sender_id"`
	Content   string             `json:"content"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID           pgtype.UUID        `json:"id"`
	Username     string             `json:"username"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}
